""" What is string slicing in python ?
    String slicing is a way to create a substring by extracting elements from the original string.
    We can specify the start index and the end index,
     and the substring will be generated by extracting the elements between these two indices.
    The syntax for string slicing is:
    string[start:end]
    Here, the start index is inclusive, and the end index is exclusive.
    This means that the substring will include the character at the start index but not the character at the end index.
    If the start index is not specified, the substring will start from the beginning of the string.
    If the end index is not specified, the substring will go to the end of the string.
Example:
"""
string = "hello"
substring = string[1:4]
print(substring)  # Output: "ell" it will show from 1 to 3 index
substring = string[0:3]
print(substring)  # Output: "hel" it will show from 0 to 2 index
substring = string[:3]
print(substring)  # Output: "hel" it will show from automatically undersaed by python 0 to 2 index
"""
    In this example, the substring will start from the character at index 1 (inclusive) and end at the character at index 4 (exclusive),
     resulting in the substring "ell" being extracted from the original string "hello".

# For function we use: () parenthesis
# for slicing we use [] square brackets
# for indexing we use [] square brackets
# for list we use [] square brackets
# for dictionary we use {} curly brackets
# for set we use {} curly brackets
# for tuple we use () parenthesis
# for generator we use () parenthesis

Neagtive indexing:
    Python also supports negative indexing, where the index is counted from the end of the string.
    For example, the last character of a string has an index of -1, the second-to-last character has an index of -2, and so on.
    We can use negative indices in string slicing to extract substrings from the end of the string.

Example:
"""
a="shubham"
print(a[0:-3])
Output: "shub"

"""
    In this example, it will 1st checak the whole length of string then it will mminus(-) it by 3
    lenth of string is =7 then 7-3=4
    so it will show from 0 to 4 index of string
    so the output will be "shub" = 0,1,2,3 not 4 index
"""

b = "shubham"
print(b[-4:-1])


#exce
c="Harry"
print(c[-4:-2])

